title: Yen-Hung Chen
remote_theme: daattali/beautiful-jekyll
show_author: false
author: ""
navbar-links:
  EN: "/"
  中文: "/zh_index.html"

paginate: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
